#! /bin/bash

cd /home/david/work/ror/qiongerdai

log_prefix=`date +%Y-%m-%dT%H_%M`

env=development

rake RAILS_ENV=${env} spider:crawl >log/${log_prefix}.crawl.${env}.out 2>&1
rake RAILS_ENV=${env} spider:downimg >log/${log_prefix}.downimg.${env}.out 2>&1
